#!/usr/bin/env python3
"""Capture garden/woodland and generated swamps with the actual packaged app.

Prepare and check the worlds with test-garden-rooms.py/test-swamp-rooms.py first.
Every tileset receives a fresh copy of the same isolated checkpoint.
"""
import argparse
import html
import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location('review', ROOT/'scripts/build-ice-cloud-review.py')
review = importlib.util.module_from_spec(spec)
spec.loader.exec_module(review)
GALLERY = ROOT/'.artifacts/garden-swamp-review.html'


def capture(kind, classic=False, rows=None, resume=False):
    if rows is None:
        rows = json.loads((ROOT/f'.artifacts/{kind}-rooms-prepared.json').read_text())
    output = ROOT/f'.artifacts/{kind}-rooms-native.json'
    results = json.loads(output.read_text()) if resume and output.exists() else []
    for row in rows:
        metadata = row['metadata']
        assert metadata['engine'] == review.shapes.tour.digest(review.shapes.tour.RES/'engine/nethack'), 'Reprepare after rebuilding the engine'
        assert metadata['app'] == review.shapes.tour.digest(review.shapes.tour.APP/'Contents/MacOS/NetHackAtlas'), 'Reprepare after rebuilding the app'
        for tileset in review.NAMES:
            if not classic and tileset in ('lantern','soot-and-brass-classic'):
                continue
            existing = next((r for r in results if r['sourceCheckpoint']==row['run'] and r['tileset']==tileset), None)
            if existing and existing['engine']==metadata['engine'] and existing['app']==metadata['app'] and Path(existing['screenshot']).exists():
                continue
            if existing:
                results.remove(existing)
            result = review.shapes.native(row, tileset)
            observed = review.cells(Path(result['run'])/'diagnostics.jsonl.engine.jsonl')
            x,y,w,h = metadata['shapeBounds']
            visible = [c for c in observed if x <= c['x'] < x+w and y <= c['y'] < y+h]
            assert visible, (kind, tileset)
            assert all('groundTile' not in c for c in observed if c['tile'] in (1469,1470))
            terrain = {tile for c in visible for tile in (c['tile'],c.get('groundTile')) if tile is not None}
            assert set(metadata['testTerrainTiles']) <= terrain, (kind,tileset,terrain)
            result.update(kind=kind, mode=metadata['mode'], bounds=metadata['shapeBounds'],
                          displayedTerrain=sorted(terrain), setup=metadata['setup'],
                          sourceCheckpoint=row['run'], engine=metadata['engine'], app=metadata['app'],
                          unchangedArtwork=True, noHiddenGround=True, nativeVerified=True)
            results.append(result)
            output.write_text(json.dumps(results,indent=2)+'\n')
            print('PASS',result['label'],tileset,result['screenshot'],flush=True)
    return results


def gallery():
    body = ['<!doctype html><html lang="en"><meta charset="utf-8">',
            '<meta name="viewport" content="width=device-width,initial-scale=1">',
            '<title>Gardens, woodland and swamps: review</title>',
            '<style>body{background:#101719;color:#e5e8e1;font:17px system-ui;max-width:1500px;margin:32px auto;padding:0 24px}'
            'h1,h2{font-family:Georgia,serif}a{color:#d6bb84}.pair{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin:20px 0 42px}'
            'img{width:100%;display:block;border:1px solid #485854;border-radius:6px}p{line-height:1.5;max-width:1000px}'
            '@media(max-width:900px){.pair{grid-template-columns:1fr}}</style>',
            '<h1>26 and 27: gardens, woodland and swamps</h1><p>Actual packaged-app screenshots using existing shipped artwork. '
            'Each tileset receives a copy of the same saved world. Click a screenshot for full size. Ready for your review; acceptance remains pending.</p>',
            '<p>Gardens are the original NetHack themed fill. Woodland paths are explicit test geometry. '
            'Swamps are generated by the original dungeon generator using its wizard room selector. '
            'Inspection reveals starting map memory and supplies documented test equipment; the dark woodland example retains normal exploration. '
            'NetHack still controls lighting, perceived occupants and movement.</p>',
            '<p><a href="../tools/tileset-preview/index.html?tileset=lantern-modern&amp;scene=garden">Interactive garden renderer fixture</a> · '
            '<a href="../tools/tileset-preview/index.html?tileset=soot-and-brass&amp;scene=swamp">Interactive swamp renderer fixture</a></p>']
    for kind,title,note in (
        ('garden','26. Gardens, trees and forest rooms','The upstream Garden turns perimeter walls into trees and adds sleeping wood nymphs and occasional fountains. '
         'It keeps ordinary room ground. The separate woodland fixtures exercise interior tree occupancy, narrow paths and unknown edges.'),
        ('swamp','27. Swamps','The upstream swamp generator alternates eligible pool and dry squares, skipping doors and existing contents. '
         'The result is a waterlogged dungeon room with fungi and aquatic creatures, not an outdoor marsh or a new dungeon branch.')):
        path = ROOT/f'.artifacts/{kind}-rooms-native.json'
        if not path.exists():
            continue
        results = json.loads(path.read_text())
        body.extend([f'<h2>{title}</h2>',f'<p>{note}</p>'])
        for label in dict.fromkeys(r['label'] for r in results):
            body.extend([f'<h3>{html.escape(label)}</h3>','<div class="pair">'])
            for result in results:
                if result['label'] != label:
                    continue
                url = Path(result['screenshot']).relative_to(GALLERY.parent).as_posix()
                name = html.escape(review.NAMES[result['tileset']])
                body.append(f'<div><h4>{name}</h4><a href="{url}"><img loading="lazy" src="{url}" alt="{name}: {html.escape(label)}"></a></div>')
            body.append('</div>')
    body.append('</html>')
    GALLERY.write_text('\n'.join(body)+'\n')
    print('REVIEW',GALLERY,flush=True)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--native', choices=('garden','swamp','all'))
    parser.add_argument('--classic',action='store_true',help='Also capture both Classic editions')
    args = parser.parse_args()
    if args.native:
        for kind in (('garden','swamp') if args.native == 'all' else (args.native,)):
            capture(kind,args.classic)
    gallery()
